# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

  # Pool name (where the agent is in)
  poolName: 'Default'

  # Agent VM image name
  vmImageName: 'arm-vm'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: $(poolName)
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  isSkippable: false
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    pool:
      name: $(poolName)
      vmImage: $(vmImageName)
    steps:
    - script: |
        echo "Running unit tests..."
        docker compose run app npm run test
        docker stop $(docker ps -a -q)
      displayName: 'Run unit tests'